apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: myproject-ns

data:
  PORT: "3000"
  MONGO_DB_NAME: "k8s-demo"
  MONGO_URI: "mongodb://mongo-service:27017/k8s-demo"