apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: myproject-ns

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: docker-backend:latest

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort:  3000

          env:
            - name: PORT
              value: "3000"

            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/k8s-demo"