apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: {{ .Values.backendConfig.port | quote }}
  MONGO_DB_NAME: {{ .Values.backendConfig.mongoDbName | quote }}
  MONGO_URI: {{ .Values.secrets.mongoUri | quote }}
