apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.service.mongo.port }}
      targetPort: {{ .Values.service.mongo.targetPort }}
  type: {{ .Values.service.mongo.type }}
