name: Deployment Validation

on:
  push:
    branches:
      - main
    paths:
      - 'demo-k8s-project/k8s-demo-chart/**'
      - 'values-prod.yaml'
      - '.github/workflows/deploy.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'demo-k8s-project/k8s-demo-chart/**'
      - 'values-prod.yaml'

jobs:
  validation-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Helm Lint
        run: |
          helm lint ./demo-k8s-project/k8s-demo-chart

      - name: Helm Template Validation (Default Values)
        run: |
          helm template myapp ./demo-k8s-project/k8s-demo-chart

      - name: Helm Template Validation (Production Values)
        run: |
          helm template myapp ./demo-k8s-project/k8s-demo-chart --values ./values-prod.yaml
